name: dating_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  country_code_picker: ^3.0.0
  pinput: ^3.0.1
  percent_indicator: ^4.2.3  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: Nunito
      fonts:
      - asset: assets/fonts/Nunito-Regular.ttf
  
  
  
  
  
  
  
  
