name: dating_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  country_code_picker: ^3.0.0
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  google_maps_flutter: null
  image_picker: ^1.0.4
  percent_indicator: ^4.2.3
  permission_handler: ^11.0.1
  pinput: ^3.0.1
  timer_count_down:
  fluttertoast: ^8.2.2
  http: ^1.1.0
  shared_preferences:

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
